# 应用服务 WEB 访问端口
server:
  port: 8080
#数据库连接
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/webstudy
    username: root
    password: 123456
#mybatis
mybatis:
  configuration:
    #开启mybatis的日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启数据库表字段 到 实体类属性的驼峰映射
    map-underscore-to-camel-case: true

#  #下面这些内容是为了让MyBatis映射
#  #指定Mybatis的Mapper文件
#mybatis.mapper-locations=classpath:mappers/*xml
#  #指定Mybatis的实体目录
#mybatis.type-aliases-package=com.ghrlearn.tlias.mybatis.entity
